---
grails:
    profile: web
    codegen:
        defaultPackage: tm.binding.registry
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    cors:
        enabled: true

    gsp:
        tldScanPattern: classpath*:/META-INF/*.tld

#   This enables the database migration plugin to, when the webserver starts, recreate the database from the content
#   in the changelog.groovy file.
    plugin:
        databasemigration:
            updateOnStart: true
            updateOnStartFileName: changelog.groovy
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
management:
    endpoints:
        enabled-by-default: false
        jmx:
            unique-names: true

server:
    tomcat:
        max-swallow-size: -1

---
hibernate:
    format_sql: true
    cache:
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
    search:
        default:
            indexBase: '/opt/tbr/lucene'
            indexmanager: near-real-time
            directory_provider: filesystem

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: admin
    password: admin11!

---

environments:
    development:
        dataSource:
            properties:
                testOnBorrow: true
                testWhileIdle: true
#           A dbCreate value of 'none' allows the database migration plugin to always recreate the database from changelog.groovy
            dbCreate: none

#           During development need to specify the database host as 'localhost' since the database migration command scripts
#           need access to the database server.
            url: jdbc:mysql://localhost:3376/binding_registry?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    production:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://tbr_database:3306/binding_registry?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
